const BRASIL = {
    nome: "República Federativa do Brasil",
    nomeCurto: "Brasil",
    capital: "Brasília (Distrito Federal)",
    continente: "América do Sul",
    populacao: 203062512,
    popAno: 2022,
    popFonte: "Censo IBGE 2022",
    area: 8515767,
    areaUnidade: "km²",
    areaFonte: "IBGE 2022",
    densidade: 23.8,
    densFonte: "IBGE 2022",
    populacaoUrbana: "87,3%",
    popUrbFonte: "Censo IBGE 2022",
    pib: 11000000000000,
    pibAno: 2023,
    pibFonte: "IBGE Contas Nacionais 2023",
    pibPerCapita: 50193,
    pibpcFonte: "IBGE 2023",
    idh: 0.754,
    idhPosicao: 89,
    idhAno: 2022,
    idhFonte: "PNUD 2022",
    gini: 0.518,
    giniAno: 2023,
    giniFonte: "IBGE PNAD Contínua 2023",
    rendaMedia: 2849,
    rendaMedFonte: "IBGE PNAD Contínua 2023",
    moeda: "Real (R$)",
    lingua: "Português (oficial)",
    linguaFonte: "Constituição Federal 1988",
    governo: "República Federativa Presidencialista",
    govFonte: "Constituição Federal 1988",
    numEstados: 26,
    numMunicipios: 5570,
    numMunFonte: "IBGE 2022",
    fronteira: ["Argentina", "Bolívia", "Colômbia", "Guiana Francesa (FR)", "Guiana", "Paraguai", "Peru", "Suriname", "Uruguai", "Venezuela"],
    litoral: 7367,
    litoralFonte: "Marinha do Brasil",
    clima: "Predominantemente tropical (Equatorial, Semiárido, Tropical de Altitude, Subtropical)",
    biomas: [
        { nome: "Amazônia", areaPct: 49.5 },
        { nome: "Cerrado", areaPct: 23.3 },
        { nome: "Mata Atlântica", areaPct: 13.0 },
        { nome: "Caatinga", areaPct: 9.9 },
        { nome: "Pampa", areaPct: 2.3 },
        { nome: "Pantanal", areaPct: 1.8 }
    ],
    biomaFonte: "IBGE 2022",
    bandeira: {
        descricao: "Retângulo verde com losango amarelo, círculo azul com 27 estrelas brancas (constelações do Cruzeiro do Sul, Virgem, Cão Maior, etc.) e faixa branca com 'Ordem e Progresso'.",
        verde: "As matas e florestas brasileiras",
        amarelo: "As riquezas minerais (ouro)",
        azul: "O céu e os rios",
        branco: "A paz",
        estrelas: "26 estados + Distrito Federal",
        lema: "Ordem e Progresso (Auguste Comte)",
        adocao: "19 de novembro de 1889",
        criador: "Raimundo Teixeira Mendes, Miguel Lemos, Manuel Pereira Reis",
        desenho: "Décio Vilares",
        bandFonte: "Lei 5.700/1971"
    },
    hino: {
        titulo: "Hino Nacional Brasileiro",
        letra: "Joaquim Osório Duque Estrada",
        musica: "Francisco Manuel da Silva",
        adocao: "1890 (música) / 1922 (letra)",
        estrofes: [
            "Ouviram do Ipiranga as margens plácidas\nDe um povo heroico o brado retumbante,\nE o Sol da Liberdade, em raios fúlgidos,\nBrilhou no céu da Pátria nesse instante.",
            "Se o penhor dessa igualdade\nConseguimos conquistar com braço forte,\nEm teu seio, ó Liberdade,\nDesafia o nosso peito a própria morte!",
            "Ó Pátria amada,\nIdolatrada,\nSalve! Salve!",
            "Brasil, um sonho intenso, um raio vívido\nDe amor e de esperança à terra desce,\nSe em teu formoso céu, risonho e límpido,\nA imagem do Cruzeiro resplandece.",
            "Gigante pela própria natureza,\nÉs belo, és forte, impávido colosso,\nE o teu futuro espelha essa grandeza.",
            "Terra adorada,\nEntre outras mil,\nÉs tu, Brasil,\nÓ Pátria amada!",
            "Dos filhos deste solo és mãe gentil,\nPátria amada,\nBrasil!",
            "Deitado eternamente em berço esplêndido,\nAo som do mar e à luz do céu profundo,\nFulguras, ó Brasil, florão da América,\nIluminado ao sol do Novo Mundo!",
            "Do que a terra mais garrida\nTeus risonhos, lindos campos têm mais flores;\n'Nossos bosques têm mais vida',\n'Nossa vida' no teu seio 'mais amores'.",
            "Ó Pátria amada,\nIdolatrada,\nSalve! Salve!",
            "Brasil, de amor eterno seja símbolo\nO lábaro que ostentas estrelado,\nE diga o verde-louro dessa flâmula\n— Paz no futuro e glória no passado.",
            "Mas, se ergues da justiça a clava forte,\nVerás que um filho teu não foge à luta,\nNem teme, quem te adora, a própria morte.",
            "Terra adorada,\nEntre outras mil,\nÉs tu, Brasil,\nÓ Pátria amada!",
            "Dos filhos deste solo és mãe gentil,\nPátria amada,\nBrasil!"
        ],
        hinoFonte: "Decreto 15.671/1922"
    },
    cargos: {
        presidente: { qtd:1, salario:39293.32, fonte:"Teto constitucional STF", nota:"Sem verba indenizatória" },
        vicePresidente: { qtd:1, salario:35000, fonte:"Estimativa — consulte", nota:"Verba indenizatória não inclusa" },
        senadores: { qtd:81, salario:39293.32, fonte:"Senado Federal — Resolução SF n° 1/2023" },
        deputadosFederais: { qtd:513, salario:39293.32, fonte:"Câmara dos Deputados — Ato da Mesa 136/2023" },
        deputadosEstaduais: { qtd:1059, salario:29469.99, fonte:"75% do teto constitucional — consulte cada AL" },
        governadores: { qtd:27, salario:35000, fonte:"Média nacional — varia por UF (consulte)" },
        viceGovernadores: { qtd:27, salario:25000, fonte:"Estimativa — consultar dados oficiais" },
        prefeitos: { qtd:5570, salario:20000, fonte:"Média nacional — varia por porte municipal (consulte)" },
        vicePrefeitos: { qtd:5570, salario:12000, fonte:"Estimativa — consultar dados oficiais" },
        vereadores: { qtd:58000, salario:10000, fonte:"Estimativa nacional — consulte cada Câmara Municipal" }
    },
    cargosFonteGeral: "Teto constitucional do funcionalismo público: STF (R$ 41.650,92 em 2025). Subsídios de senadores e deputados federais fixados pelo Congresso Nacional. Demais valores são estimativas baseadas em médias nacionais — consulte fontes oficiais.",
    ultimaAtualizacao: "Junho de 2026",
    observacao: "Verifique a veracidade e atualize os dados em ibge.gov.br, atlasbrasil.org.br. Dados de municípios: consulte IBGE para valores oficiais."
};
